version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /app/frontend
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
    groups:
      frontend:
        patterns: ["*"]
